front_page:
    path: intcomeximport/
    methods: [GET]
    defaults:
        _controller: 'IntcomexImport\Controller\AdminHomeController::frontPage'
        _legacy_controller: AdminHome
        _legacy_link: AdminHome